version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: my_second_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: dim_product
    description: "Products dimension"
    columns:
      - name: dky_product
        description: ""
        tests:
          - unique
          - not_null
      - name: des_product
        description: ""
        tests:
          - unique
          - not_null

  - name: dim_status
    description: "Order status dimension"
    columns:
      - name: dky_status
        description: ""
        tests:
          - unique
          - not_null
      - name: des_status
        description: ""
        tests:
          - unique
          - not_null
