version: 2

models:
  - name: fat_orders
    description: "A starter dbt model"
    columns:
      - name: dky_day
        description: "day"
      
      - name: dky_status
        description: ""

      - name: dky_product
        description: ""
 
      - name: qty_orders
        description: ""

      - name: num_price
        description: ""

      - name: qty_distinct_customers
        description: ""
 
      - name: qty_customers
        description: ""
      
      - name: qty_closed_orders
        description: ""
      

  - name: dim_product
    description: "Products dimension"
    columns:
      - name: dky_product
        description: ""
        tests:
          - unique
          - not_null
      - name: des_product
        description: ""
        tests:
          - unique
          - not_null

  - name: dim_status
    description: "Order status dimension"
    columns:
      - name: dky_status
        description: ""
        tests:
          - unique
          - not_null
      - name: des_status
        description: ""
        tests:
          - unique
          - not_null
